### ISSUE TITLE
I got some issues

### ISSUE THREAD

**Issue by LUCYFERRRS** [RobertAndion/Discord_Music_Bot#2]
Hey Mr Robert i have some problem to install some of tools, can i get your discord or something to talk with you
P.s sorry for faut I'm french
My discord:Lucifer_MorningStar#6880

**Comment by RobertAndion** [comment]
Hello, I haven't considered making a discord for it until now but I suppose I can. What issue are you having? Is it when you are trying to install lavalink, dotenv and dependencies like that? If so its through pip when you install python3. pip install python-dotenv for example will install dotenv. pip install lavalink will install lavalink. If you have other versions of python and depending on your os you may have to do pip3 install. I hope this helps, if not describe your issue a little bit and I will try to help from here. Otherwise I may create a discord for it. Thank you
